openapi: 3.0.3
info:
  title: Marketplace API
  description: API for a marketplace application
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server
paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Unauthorized
