# version: '3.8'

services:
  # Node.js application service
  tenant-service:
    build: .
    environment:
      - TENANT_ID=47dd6b24-0b23-46b0-a662-776158d089ba
      - AUTH_MS_URL=http://host.docker.internal:8000
      - TENANT_MS_URL=http://host.docker.internal:8003
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8003:8003"
    depends_on:
      - db

  # PostgreSQL database service
  db-tenant:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"    
    volumes:
      - ./tenant/db/schema:/docker-entrypoint-initdb.d  
      - /var/lib/postgresql/data